### ISSUE TITLE
Requirement that Auth provides value to the user

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/app-mining#163] opened 2019-10-07 11:07 UTC
Apps like https://startuplist.pro/ are trying to game App Mining. They add Blockstack Auth just to participate in App Mining, but auth provides no value.

What about a requirement that auth should provide value to the user? e.g. through a personalized experience, additional features, synching data.

**Comment by ViniciusBP** [comment] 2019-10-07 11:39
Many apps are doing this and usually they rank better on TryMyUI, because not even testers log in. But they should not even be considered a Blockstack App.

There are also some using Blockstack as an optional sync, which almost no one uses. Those apps will become leaders once PH is removed. They dont help Blockstack gain adoption or visibility. This should be addressed , maybe using input from testers?

**Comment by larrysalibra** [comment] 2019-10-12 15:56
Any concrete suggestions on how this could be scored? Would a subjective rating system be acceptable to the community?

**Comment by friedger** [comment] 2019-11-08 09:26
This looks like a duplicate of #137

**Closed** 2019-11-12 17:12 UTC
