### ISSUE TITLE
debut App - March App Mining Feedback

### ISSUE THREAD

**Issue by kkomaz** [blockstack/app-mining#61] opened 2019-03-19 23:14 UTC
There's a lot to say but going to try my best to keep it concise and to the point.  💯 

### Issue 1 - Democracy Earth
- The general feedback I got from the Blockstack team regarding this situation is that there is no great way for developers to engage with democracy earth voters.  One aspect of engagement is the democracy earth debate function in [vote.blockstack.org](http://vote.blockstack.org).  However, this is not a great forum.  I know it's a lot asking voters why they vote the way they do, but as developers we should get some REAL feedback on the problems of our application, whether it be long or short term.  The only posts that exist in the **debut** debate forum are my own messages.

![demo](http://g.recordit.co/zJwfNXyeUP.gif)

- As a pretty active member in the Blockstack community, I get constant feedback and encouragement to not be discouraged by the app mining results.  I understand when I first started, I submitted a pretty weak project because it was done as an experiment.  This month I really tried to add a professional feel by improving the landing page, adding helper icons, etc but it seems that effort was unrecognized based on the results.

<img width="444" alt="Screenshot of ScreenFloat (3-19-19, 5-42-55 PM)" src="https://user-images.githubusercontent.com/8473884/54643920-70c00080-4a6e-11e9-9079-2abef057f0b7.png">

- Although I love the encouragement, there is a limited bandwidth of my time that I can commit to debut.  If a decentralized social networking application is not what democracy earth voters want, then maybe it's time to pivot?  There are vastly superior social networking sites out there... twitter, facebook, instagram etc and to a certain extent convenience > privacy.  However, I thought the overall goal was to create an incentive where decentralized apps, although RIGHT NOW, can't compete with those giants in terms of features, can provide an alternative to them.  

- I really believed being on the forefront of Implementing Radiks in my app and creating one of the first apps where you could interact with other *Blockstack* users was something that was truly missing.  Prior to debut, the only way I knew of other Blockstack users was [explorer.blockstack.org](explorer.blockstack.org).  I really can't see how my development effort equates to **87 cents**.  Maybe it's not that important right now?

### Issue 1 Proposed Recommendation
- Is there a slack channel we can engage with the investors?  If not, can we enforce some type of intermediary step to explain why a certain app is being downvoted or upvoted.
- Engagement is needed as it helps the overall long term goals of competing with centralized applications.
- Is the long term goal of Blockstack apps scoped to a specific type?  Do we need to limit our scope of apps to a specific set to ensure greater adoption?

---
### Issue 2 - App Mining scoring system
- Scanning the top 30 apps I'm noticing a certain trend.  

#### Note specific apps
- Rank 1: Graphite - Encrypted, shareable, decentralized personal data
- Rank 5: Blockusign - Encrypted Document Signing
- Rank 9: AirText - Create your own decentralized blog
- Rank 10: Graphite Publishing - Graphite Publishing is a decentralized blogging platform with full site design in addition to authoring tools.
- Rank 11: Note Riot -  NoteRiot is your private, secure, note keeping tool. Notes are encrypted and accessible across all of your devices and platforms.
- Rank 12: Sigle - A beautiful decentralized and open source blog maker
- Rank 19: DPage - Publish web content on the decentralized internet
- Rank 21 - Forms.id - Privacy-centric, alternative to Google Forms

#### Photo saving apps
- Rank 6: Recall - Safely store and access your photos
- Rank 7: Encrypt My Photos - End-to-End Encrypted Photo Storage
- Rank 23: Block Photos - Solution for storing your photo album in the cloud

#### Comments
I don't want to criticize any apps.  That's not my intention.  The numbers are pretty evident though, Note/Blog style applications from simple to complicated technologies are the winners in the Blockstack app mining program.

### Issue 2 Proposed Recommendation
- ### **CATEGORIES**
- I would love to see app mining rank based on categories.  This is pretty obvious based on the 3 months of results that I made the wrong choice in building debut (if my incentive was also only app mining rewards)
- Especially with TryMyUI testers, engaging with an application that is relatively simple like uploading a file or writing content into a form SHOULD have a higher score than more complicated applications that want to establish relationships between different blockstack users such as crowdfunding, engagement, etc
- Testers are also more likely to bring *bias* when it comes to social networking apps because it is natural for them to compare it to facebook, instagram, twitter etc without realizing the benefits of decentralized secure storage.  With note taking apps, it is somewhat siloed in that interactions between other users is very minimal.

---
### Issue 3 - TryMyUI Testers
- It hurts watching these videos.  I will gladly accept feedback that makes relative sense to my application.
- Very frustrating when users are not following the TryMyUI instructions and as a result receive all 1's.
- Majority of the testers are complaining about signing into (or signing up) for Blockstack.  This has nothing do with my application and debut is getting dinged for that.  Below is a screenshot of a 20 min video where the user ended the video without ever using my app.  This user described Blockstack as scary and not something I would trust.  Not debut... Blockstack.  sigh.

![Screenshot of Preview (3-19-19, 7-11-11 PM)](https://user-images.githubusercontent.com/8473884/54647972-e8942800-4a7a-11e9-866a-57df95316e4e.png)

- I did get some good feedback from people who are being able to get past the log in phase.  They loved the idea but felt that it was somewhat incomplete which I totally understand. 
 Besides Graphite and a few other applications, are there any applications that are truly ready to go in terms of full adoption?  (Which leads into my question below)

---

### App Mining Score Questions
- Did I just ruin my overall app mining score by submitting too early?  @xanbots  // @pstan26 
- Should the better approach have been WAITING until everything was flushed out?  Will I always be fighting my way to the top carrying the burden of my negative early scores?
- If I had a choice between 87 cents + lower score vs. not submitting.  I think you know the answer.

**Comment by hstove** [comment] 2019-03-20 16:46
Hey @kkomaz , there is some solid feedback in here. The problem is that there are three separate suggestions in here, so we can't effectively track them separately. Would it be possible to split these into three separate issues? If you don't have time, I can do it for you, and I'll just copy/paste what you said.

**Comment by kkomaz** [comment] 2019-03-20 17:29
Sure will @hstove I think a lot of the issues are addressed in other forums except my categories.  So once I get those created I'll close this issue.

**Comment by jeffdomke** [comment] 2019-03-21 23:31
@kkomaz can we please close this issue? All spit? Closing, just let me know if I need to reopen.

**Closed by jeffdomke** 2019-03-21 23:31 UTC
