### ISSUE TITLE
Product Hunt should be minimized in the November scoring

### ISSUE THREAD

**Issue by njordhov** [blockstack/app-mining#179] opened 2019-11-20 19:30 UTC
**I petition that Product Hunt influence is minimized in the November app mining results by replacing the Last Month score with the same calculated with PH removed.**

Product Hunt was supposed to “no longer be included in the scores for November.” Yet 1/4 of the Audit score still include Product Hunt as factor, as 25% of the score is taken from last month’s score.

The consequence is that apps that spiked their Product Hunt scores continue to have an unfair advantage, while apps that played fair are hampered.

Further discussion and community feedback at:
https://blockstack.slack.com/archives/CAVRMN2CR/p1574040767115600

**Comment by hstove** [comment] 2019-11-20 19:50
Hey, thanks for posting this here.

I am definitely against this change. We never promised that PH scores would be removed from the 'memory function', only that it would be removed as a reviewer.

This is consistent with every change we've ever made. We've removed reviewers in the past, and have made tweaks to the scoring methods (for example, with Awario this month). We have never retroactively changed the memory function to account for these, and I'm not sure why PH would be any different.

The memory function is strictly stated as "25% of your score from last month" - which does include any previously changed or removed score criteria.

Additionally, this would add a ton of operational complexity. For every change we ever make, we'd have to make different results for on past data using our new methods. App.co also computes its own memory function, and stores the "official" results in its database. In order for us to make this change, we'd have to write a bunch of functionality into app.co to say "For this month, you need to use these totally different scores for past months". And we'd have to upload all those newly calculated old results onto app.co. The memory function is recursive - so we'd have to do this for every App Mining month ever, for every single change we make.

It's also disingenuous to say your score is 25% from Product Hunt. It's 25% of 25% (since there are 4 reviewers). And then it's 75% of that, because there was a memory function that month as well. So we're already down to less than 5% of this month's score from PH, and next month it'll be less than 1%.

I understand why this request is being made, however, we simply could not make this change in time for the current payouts cycle, even if we wanted to. And, to be consistent, we'd have to do this for every change ever, including things like Democracy Earth, which still does have a tiny effect on your scores!

I think the real beef you might have here is with the memory function. If the memory function had less weight, this would be even less of an issue.

**Comment by dantrevino** [comment] 2019-11-20 20:24
I cant argue about the technical complexity.  I don't understand it, but I completely trust @hstove .  What I think is disappointing is that the issues with PH were called out over a year ago, we finally remove them from being a reviewer, and now we learn that they will continue to have lingering impact to *honest* app miners. 

This is sad.

**Comment by hstove** [comment] 2019-11-20 20:31
@dantrevino , thank you for that. You mentioned on Slack "I dont get why we cant wrap if (month > 2019-11), around the memory function.". Yes, it could possibly be easier to make a one-time change for this, but it would still take time, and couldn't be fully ready in 48 hours for payouts. However, that wouldn't address the point that this would be inconsistent with how we've always behaved around changes to reviewers and scoring methods, or even to address how PH still is included in not just October's results, but every result, ever.

I am not trying to argue whether PH having a lingering effect is good or bad - I completely understand the concern here. I just want us to have consistency and not have to make one-time decisions for a certain change that people feel more strongly about. There will be many more changes to scoring, and things will get abused, and we'll try and fix them. Let's just be consistent. Which, again, is why I think the memory function itself is more of the root cause here.

**Comment by dantrevino** [comment] 2019-11-20 20:45
@hstove agreed(ish).  The specific issue here is the memory function, however the larger point, in my mind is the very same consistent reaction that you refer to.

I've heard some developers refer to some of the previously corrected issues as "gaming the system", or worse "gaming the game"... 

I do not see these as "gaming" ... these issues are an _ATTACK_ on the protocol.  Reactions should be appropriate to the attack.  Unfortunately, while App Mining puts in a rewards mechanism for good behavior, it appears to put an even *better* reward mechanism for attacks.

I do not think its unreasonable to suggest that this should be fixed sooner, rather than let the lingering effects continue.

**Comment by cuevasm** [comment] 2019-11-20 21:06
I'm just generally not into a revisionist history approach to App Mining. Fact of the matter is, people did a good job at scoring in the system as it was. Just because we're getting better and that is no longer rewarded, doesn't mean it didn't happen. I realize this is a bit philosophical, but operating this way makes sure we find weaknesses and correct gaming rapidly, since we're not going to simply delete and act like it didn't happen later on, it's permanent in that way and I personally find that good, a great motivator to move more quickly than we have, if anything. For this reason, plus all the complexities, I don't think going back in time and tinkering with what was established is fair, right, or feasible.

**Comment by joberding** [comment] 2019-11-20 22:13
I don't think the request was to rewrite all of history but that the percentage of impact that Product Hunt has on scores in November, December and going forward should be eliminated. There are a number of hidden costs in failing to take action. Bottom line, good ethical people lose.

**Comment by cuevasm** [comment] 2019-11-20 22:26
My understanding of Hank's post is that doing this WOULD require rewriting a lot of history, often times with data we may not have or that was meant to be purely dry-run

**Comment by wilsonbright** [comment] 2019-11-21 03:47
The understanding is that the Results of the 'No PH Run' score circulated during October App Mining were to ensure the weight given to PH has to be removed completely without impacting upcoming months. Carrying forward still has an impact on the upcoming ranking for many apps in the coming month as seen from the report here https://docs.google.com/spreadsheets/d/1OF2rUTMTdDo9ahVqHfrZ7RAdsMrp5JSHfqXKrGrG1C0/edit#gid=1365181561

**Comment by njordhov** [comment] 2019-11-21 04:17
> To truly remove PH from the memory function, we'd have to recalculate results for every month that PH existed.

**The petition does NOT request that Product Hunt is completely eradicated** from the November app mining scores, only that the impact of the Product Hunt scores from October are subtracted. It doesn't have to be done recursively all back to the beginning of app mining. Better not let the perfect get in the way of the good.

Product Hunt continues to have a substantial impact, with one app dropping in rank from 23 to 43 if just the PH score from October is excluded from the equation. We can blunt the lingering effect now. Extra bonus if you can eliminate PH a couple of months back, but if that's not an option, eliminating the impact from October would be a major improvement.

**Comment by ntheile** [comment] 2019-11-23 01:15
Great to see ProductHunt finally getting the axe! Kudos to those who fought long and hard on this issue. Not great to see these lingering side affects for apps who launched early....it kind of puts the OG's at a disadvantage. Would re-launching an app be a possibility to fixing the memory function issue?

**Comment by njordhov** [comment] 2019-11-23 05:18
The lingering impact of Product Hunt is particularly noticeable for apps that launched in October, with **1/12 of their October PH score making it into their November final score.** For example, one app launched in October with a PH of 2.245, boosting their November score with 0.187 for a **gain in ranking of around 30 positions**. In December, they’ll still benefit from a 0.04 point gain in their score coming from PH, plausibly increasing their rank with ten positions or more.

**Closed** 2019-12-03 17:37 UTC
