### ISSUE TITLE
Reference Principles of Blockstack apps

### ISSUE THREAD

**Issue by friedger** [blockstack/app-mining#38] opened 2019-02-20 20:43 UTC
Does an app in the app mining program need to follow the principles of Blockstack apps as described in https://docs.blockstack.org/develop/dapp_principles.html#blockstack-dapp-principles ?

**Comment by jeffdomke** [comment] 2019-02-21 15:53
In short yes, or at least our goal is to do so, that is why we have this epic: Proposal: Blockstack "Good Citizen" reviewer: #8 

I'm suggesting this is a duplicate of that issue and will close.

**Closed by jeffdomke** 2019-02-21 15:53 UTC
